# Generated by Django 4.2.7 on 2023-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="puplicada",
            field=models.BooleanField(default=False),
        ),
    ]
